services:
  backend:
    build: ./backend/
    container_name: "all-backend"
    restart: unless-stopped
    ports:
      - 2026:8001
    environment:
      PORT: 8001
      database_url: postgresql://postgre:passgre@all-postgresql:5432/english
      app_name: "English courses"
      debug: "true"
      static_dir: "static"
      images_dir: "static/images"
      cors_origins: '["*"]'
    volumes:
      - ./backend/.backend_data:/app/static
    depends_on:
      - database
    networks:
      - all

  database:
    image: 'postgres:15.15'
    container_name: "all-postgresql"
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: passgre
      POSTGRES_DB: english
    networks:
      - all
    volumes:
      - ./backend/.postgre_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:9.10'
    container_name: "all-pgadmin"
    restart: unless-stopped
    ports:
      - 2028:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pogre@bk.ru
      PGADMIN_DEFAULT_PASSWORD: pagre
    depends_on:
      - database
    networks:
      - all
    volumes:
      - ./backend/.pgadmin-data:/var/lib/pgadmin

  frontend:
    build:
      context: ./frontend/
      args:
        VITE_API_URL: "http://127.0.0.1:2026"
    container_name: "all-frontend"
    restart: unless-stopped
    ports:
      - 2027:80
    depends_on:
      - backend
    networks:
      - all

  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: all-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/.prometheus_data:/prometheus
    networks:
      - all

  grafana:
    image: grafana/grafana:12.1
    container_name: all-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datsources/datasource.yml
      - ./monitoring/.grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - all


networks:
  all:
    external: false
