services:
  backend:
    build: ./backend/
    container_name: "all-backend"
    restart: unless-stopped
    ports:
      - 2026:8001
    environment:
      PORT: 8001
      database_url: postgresql://postgre:passgre@all-postgresql:5432/english
      app_name: "English courses"
      debug: "true"
      static_dir: "static"
      images_dir: "static/images"
      cors_origins: '["*"]'
    volumes:
      - ./backend/.backend_data:/app/static
    depends_on:
      - database
    networks:
      - all

  database:
    image: 'postgres:15.15'
    container_name: "all-postgresql"
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: passgre
      POSTGRES_DB: english
    networks:
      - all
    volumes:
      - ./backend/.postgre_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:9.10'
    container_name: "all-pgadmin"
    restart: unless-stopped
    ports:
      - 2028:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pogre@bk.ru
      PGADMIN_DEFAULT_PASSWORD: pagre
    depends_on:
      - database
    networks:
      - all
    volumes:
      - ./backend/.pgadmin-data:/var/lib/pgadmin

  frontend:
    build:
      context: ./frontend/
      args:
        VITE_API_URL: "http://127.0.0.1:2026"
    container_name: "all-frontend"
    restart: unless-stopped
    ports:
      - 2027:80
    depends_on:
      - backend
    networks:
      - all

networks:
  all:
    external: false
