services:
  backend:
    build: .
    container_name: "backend-backend"
    restart: unless-stopped
    ports:
      - 2026:8001
    environment:
      PORT: 8001
      database_url: postgresql://postgre:passgre@backend-postgresql:5432/english
      app_name: "English courses"
      debug: "true"
      static_dir: "static"
      images_dir: "static/images"
      cors_origins: '["*"]'
    volumes:
      - ./.backend_data:/app/static
    depends_on:
      - database
    networks:
      - backend

  database:
    image: 'postgres:15.15'
    container_name: "backend-postgresql"
    restart: unless-stopped
    ports:
      - 15432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: passgre
      POSTGRES_DB: english
    networks:
      - backend
    volumes:
      - ./.postgre_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:9.10'
    container_name: "backend-pgadmin"
    restart: unless-stopped
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pogre@bk.ru
      PGADMIN_DEFAULT_PASSWORD: pagre
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - .pgadmin-data:/var/lib/pgadmin

networks:
    backend:
        external: false
